config/routes.rb
Rails.application.routes.draw do

  root :to => redirect("/posts")
  
  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	validates_presence_of :post_id
	validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates_presence_of :title
	validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name == "admin" && password == "secret"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
	<p style="color:red;", class="margin_large">
		<strong><i>Posted <%= time_ago_in_words(comment.created_at) %></i></strong>
	</p>
	<p style="font-family:verdana; color:black; font-size:20px;" class="margin_large">
		<%= h(comment.body) %>
	</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment))%>").hide();
$("#comments").prepend(new_comment);
$("#comment_<%= @comment.id %>").fadeIn("slow");
$("#new_comment")[0].reset();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/posts">Blog Away!</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">More <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="type here...">
          </div>
          <button type="submit" class="btn btn-primary">Search</button>
        </form>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<br><br>


<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, class: "horizontal" do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>

  <div class="form-group">
    <%= f.label :title, :class => "col-sm-2 control-label" %><br>
  </div>
  <div class = "form-group col-lg-7">
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  
  <br><br><br><br>
  <div class="form-group">
    <%= f.label :body, :class => "col-sm-2 control-label" %><br>
  </div>
  <div class = "form-group col-lg-7">
    <%= f.text_area :body, :rows => 8, :class => "form-control" %>
  </div>

  <br><br><br><br><br><br><br><br><br><br><br><br>
  
  <div class="form-group">
    <!-- <%= f.submit %> -->
    <%= button_tag(type: "submit", :class => "btn btn-primary margin_small") do %>
      <span class = "glyphicon glyphicon-check"></span> Post it!
    <% end %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= button_to @post, class: "btn btn-primary btn-lg margin_small", method: :get do %>
  <span class = "glyphicon glyphicon-eye-open"></span> Show
<% end %>

<br>
<%= button_to posts_path, class: "btn btn-warning btn-lg margin_small", method: :get do %>
  <span class = "glyphicon glyphicon-arrow-left"></span> Back
<% end %>

<!-- <%= link_to 'Show', @post %> -->
<!-- <%= link_to 'Back', posts_path %> -->

app/views/posts/index.html.erb
<div class="jumbotron">
  <h1>Blog Away!</h1>
  <p>Your blog, your space - Blog Away!</p><br><br>
  <%= button_to new_post_path, class: "btn btn-success btn-lg", method: :get do %>
  <span class = "glyphicon glyphicon-pencil"></span> New article!
<% end %>
</div>

<h1>Listing posts</h1>

<table class = "table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <!-- <td><%= button_to post, class: "btn btn-primary btn-lg", method: :get do %>
          <span class = "glyphicon glyphicon-eye-open"></span> See more
          <% end %>
        </td> -->
        <!-- <td><%= button_to edit_post_path(post), class: "btn btn-warning btn-lg", method: :get do %>
          <span class = "glyphicon glyphicon-edit"></span> Edit it
          <% end %>
        </td> -->
        <!-- <td><%= button_to post, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-lg" do %>
          <span class = "glyphicon glyphicon-trash"></span> Delete it
          <% end %>
        </td> -->
        
        <td><%= button_to "See more", post, method: :get, class: "btn btn-primary btn-lg" %></td>
        
        <td><%= button_to "Edit it", edit_post_path(post), method: :get, class: "btn btn-warning btn-lg" %></td>

        <td><%= link_to '<span class="glyphicon glyphicon-trash"></span>Delete it'.html_safe, post, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-lg white' %></td>
        
        <!-- <td><%= button_to "Delete it", post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-lg" %></td> -->
        <!-- <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-lg" %></td> -->

        <!-- <td><button type="button" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-edit"></span> Edit</button></td> -->
        <!-- <td><%= link_to 'Show', post %></td> -->
        <!-- <td><%= link_to 'Edit', edit_post_path(post) %></td> -->
        <!-- <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to new_post_path, class: "btn btn-success btn-lg margin_small", method: :get do %>
  <span class = "glyphicon glyphicon-pencil"></span> New article!
<% end %>

<!-- <%= link_to 'New Post', new_post_path %>  -->

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= button_to posts_path, class: "btn btn-warning btn-lg margin_small", method: :get do %>
  <span class = "glyphicon glyphicon-arrow-left"></span> Back
<% end %>

<!-- <%= link_to 'Back', posts_path %> -->

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <!-- <strong>Title:</strong> -->
  <div class = "page-header margin_small">
  	<h1><%= @post.title %></h1>
  </div>
</p>

<p class="lead margin_large">
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<br><br>

<%= button_to edit_post_path(@post), class: "btn btn-success btn-lg margin_small", method: :get do %>
  <span class = "glyphicon glyphicon-check"></span> Edit
<% end %>

<br><br>

<hr><h2 class="margin_small">Comments</h2><hr>
<div id="comments">
	<%= render :partial => @post.comments.reverse %>
</div>

<br><br>

<%= form_for([@post, Comment.new], remote: true, class: "horizontal") do |f| %>
	<div class="form-group col-lg-7">
  <p><%= f.label :body, "New Comment", :class => "control-label" %><br/>
		<%= f.text_area :body, :class => "form-control" %>
  </div>
	</p>
  <br><br><br><br><br><br>
	
  <div class="form-group">
    <!-- <%= f.submit %> -->
    <%= button_tag(type: "submit", :class => "btn btn-primary margin_small") do %>
      <span class = "glyphicon glyphicon-check"></span> Post it!
    <% end %>
  </div>
<% end %>


<br>
<%= button_to posts_path, class: "btn btn-warning btn-lg margin_small", method: :get do %>
  <span class = "glyphicon glyphicon-arrow-left"></span> Back
<% end %>

<!-- <%= link_to 'Edit', edit_post_path(@post) %> -->
<!-- <%= link_to 'Back', posts_path %> -->